export const ROUTES = {
  LOGIN: "/login",
  OVERVIEW: "/overview",
  CHAT: "/chat",
  CHAT_SESSION: "/chat/:sessionKey",
  AGENTS: "/agents",
  AGENT_DETAIL: "/agents/:id",
  SESSIONS: "/sessions",
  SESSION_DETAIL: "/sessions/:key",
  SKILLS: "/skills",
  SKILL_DETAIL: "/skills/:id",
  CRON: "/cron",
  CONFIG: "/config",
  TRACES: "/traces",
  TRACE_DETAIL: "/traces/:id",
  DELEGATIONS: "/delegations",
  USAGE: "/usage",
  CHANNELS: "/channels",
  APPROVALS: "/approvals",
  NODES: "/nodes",
  LOGS: "/logs",
  PROVIDERS: "/providers",
  TEAMS: "/teams",
  TEAM_DETAIL: "/teams/:id",
  CUSTOM_TOOLS: "/custom-tools",
  BUILTIN_TOOLS: "/builtin-tools",
  MCP: "/mcp",
  TTS: "/tts",
} as const;

export const LOCAL_STORAGE_KEYS = {
  TOKEN: "goclaw:token",
  USER_ID: "goclaw:userId",
  SENDER_ID: "goclaw:senderID",
  THEME: "goclaw:theme",
  SIDEBAR_COLLAPSED: "goclaw:sidebarCollapsed",
} as const;
